// literals.lark



%import .terminals (IDENTIFIER, _NULL, _TRUE, _FALSE, SIGNED_INTEGER, SIGNED_FLOAT, ESCAPED_STRING)

// Re-export for downstream files
// These terminals are not used in THIS file, but needed further down the chain
%import .terminals (PLUS, MINUS, MULTIPLY, DIVIDE, FLOOR, MODULO, POWER)
%import .terminals (LT, LTE, GT, GTE, IS, ISNT)
%import .terminals (AND, OR, NOT)
%import .terminals (IF, ELSE, ELIF)
%import .terminals (LIST, DICT, CALL)
%import .terminals (PRINT, ASK, RANDOM, TIME, SLEEP)
%import .terminals (STOP, SKIP, RESULT, ELLIPSIS, RAISE, ERROR)
%import .terminals (WHILE, TEST, FAIL)
%import .terminals (ACTION, THING, HAS)
%import .terminals (FROM, USE, AS, DOT)
%import .terminals (_NEWLINE, _INDENT, _DEDENT)
%import .terminals (WS, LINE_CONT, COMMENT, BLOCK_COMMENT)


// Identifier
identifier: IDENTIFIER

// Literals
?literal: null_literal
        | boolean_literal
        | number_literal
        | string_literal

null_literal: _NULL

boolean_literal: _TRUE -> true_literal
                | _FALSE -> false_literal

?number_literal: integer_literal
               | float_literal

integer_literal: SIGNED_INTEGER
float_literal: SIGNED_FLOAT

string_literal: ESCAPED_STRING
