// modules.lark



%import .expressions (identifier, expression)
%import .expressions (FROM, USE, AS, DOT, ESCAPED_STRING)

// Re-export for downstream files
%import .expressions (PLUS, MINUS, MULTIPLY, DIVIDE, FLOOR, MODULO, POWER)
%import .expressions (LT, LTE, GT, GTE, IS, ISNT)
%import .expressions (AND, OR, NOT)
%import .expressions (IF, ELSE, ELIF)
%import .expressions (LIST, DICT, CALL)
%import .expressions (STOP, SKIP, RESULT, ELLIPSIS, RAISE, ERROR)
%import .expressions (WHILE, TEST, FAIL)
%import .expressions (ACTION, THING, HAS)
%import .expressions (_NEWLINE, _INDENT, _DEDENT)
%import .expressions (WS, LINE_CONT, COMMENT, BLOCK_COMMENT)

// Import statement entry point
use_statement: use_name | use_from

// Import from a file or a named module
use_from: FROM (ESCAPED_STRING | dotted_path) use_name

// List of imported names
use_name: USE STAR_IMPORT
        | USE use_target+

use_target: identifier use_as?

// "Import all"
STAR_IMPORT: "*"

use_as: AS identifier

// Dotted path
dotted_path: identifier (DOT identifier)*
