// moon.lark

// Flat linear import order
// moon.lark <- control_flow <- modules.lark <- expressions.lark <- literals.lark <- terminals.lark



%import .control_flow (statement, simple_statement, compound_statement, expression)
%import .control_flow (_NEWLINE)
%import .control_flow (WS, LINE_CONT, COMMENT, BLOCK_COMMENT)

// Entry points
start: file_input

file_input: (_NEWLINE | statement)*

single_input: _NEWLINE | simple_statement | compound_statement _NEWLINE

eval_input: expression _NEWLINE*

// Ignored tokens
%ignore WS
%ignore LINE_CONT
%ignore COMMENT
%ignore BLOCK_COMMENT
