// terminals.lark



// Indentation (Lark post-lexer managed)
%declare _INDENT _DEDENT

// Whitespaces, newlines, line continuation

// A newline separates statements
// Absorb also subsequent lines that only contain spaces/tabs/comments/
_NEWLINE: ( /\r?\n[\t ]*/ | COMMENT )+

// Horizontal spaces (token separators), ignored by the parser
WS: /[\t \f]+/

// Allows continuing a statement on the nextline without triggering a _NEWLINE
LINE_CONT: /\\[\t \f]*\r?\n/

// Comments

// Single-line comment
COMMENT: /#[^\n]*/

// Multi-line comment
BLOCK_COMMENT: /\([\s\S]*?\)/
// BLOCK_COMMENT: /#\([\s\S]*?\)#/ // Alternative idea

// Punctuation

ELLIPSIS: "..."
DOT: "."

// Primitive Literals

_NULL: "null"
_TRUE: "true"
_FALSE: "false"

// Numbers

DIGIT: /[0-9]/
HEXDIGIT: /[0-9a-fA-F]/

INTEGER: DIGIT+
SIGNED_INTEGER: [PLUS | MINUS] INTEGER

DECIMAL: DIGIT+ "." DIGIT* | "." DIGIT+
EXP: /[eE][+-]?[0-9]+/

FLOAT: INTEGER EXP | DECIMAL [EXP]
SIGNED_FLOAT: [PLUS | MINUS] FLOAT

// Strings

_STRING_INNER: /.*?/
_STRING_ESC_INNER: _STRING_INNER /(?<!\\)(\\\\)*?/

DOUBLE_QUOTED_STRING: "\"" _STRING_ESC_INNER "\""
SINGLE_QUOTED_STRING: "'" _STRING_ESC_INNER "'"

ESCAPED_STRING: SINGLE_QUOTED_STRING | DOUBLE_QUOTED_STRING

// Identifiers

// Classic identifier
NAME: /[^\W\d]\w*/

// Emoji identifier
EMOJI: /[\U0000231A-\U0001FAFF]/
// EMOJIS: /(\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff])/g // Alternative idea

IDENTIFIER: NAME | EMOJI

// Operators
PLUS: "+"
MINUS: "-"
MULTIPLY: "*"
DIVIDE: "/"
FLOOR: "//"
MODULO: "%"
POWER: "**"

// Relational Operators (comparison)
LT: "<"
LTE: "<="
GT: ">"
GTE: ">="
IS: "is"
ISNT: "isnt"

// Logical Operators
AND: "and"
OR: "or"
NOT: "not"

// Composites
LIST: "list"
DICT: "dict"

// Classes ("thing")
THING: "thing"
HAS: "has"
DEFAULT: "default"

// Functions ("action")
ACTION: "action"
RESULT: "result"
CALL: "call"

// Native functions
PRINT: "print"
ASK: "ask"
RANDOM: "random"
TIME: "time"
SLEEP: "sleep"

// Imports / modules/
FROM: "from"
USE: "use"
AS: "as"

// Conditional Control Flow
IF: "if"
ELSE: "else"
ELIF: "elif"

// Loops
WHILE: "while"
STOP: "stop"
SKIP: "skip"
FOR: "for"
IN: "in"

// Error Handling
TEST: "test"
FAIL: "fail"
RAISE: "raise"
ERROR: "error"
ASSERT: "assert"

// Reserved keywords (unused for now)
ASYNC: "async"
AWAIT: "await"
END: "end"
GLOBAL: "global"
LAMBDA: "lambda"
NOTHING: "nothing"
PASS: "pass"
YIELD: "yield"